---

- name: Installing oh-my-zsh per user via github
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ item.username }}/.oh-my-zsh"
    update: "{{ users_ohmyzsh_update }}"
  with_items: "{{ users }}"

- name: Setting required permissions per use
  file:
    path: "/home/{{ item.username }}/.oh-my-zsh"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    recurse: yes
  with_items: "{{ users }}"

- name: Setting default shell per user to zsh
  user:
    name: "{{ item.username }}"
    shell: /usr/bin/zsh
  with_items: "{{ users }}"

- name: Deploying .zshrc
  template:
    src: home-user-zshrc.j2
    dest: "/home/{{ item.username }}/.zshrc"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    backup: yes
    mode: "0644"
  with_items: "{{ users }}"
